/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author lenov
 */
public class Dhasboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dhasboard.class.getName());

    /**
     * Creates new form Dhasboard
     */
    public Dhasboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuitemMahasiswa = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuitemDosen = new javax.swing.JMenuItem();
        menuitemCourse = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        menuitemMahasiswa.setText("Data");

        jMenuItem1.setText("Mahasiswa");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        menuitemMahasiswa.add(jMenuItem1);

        menuitemDosen.setText("Dosen");
        menuitemDosen.addActionListener(this::menuitemDosenActionPerformed);
        menuitemMahasiswa.add(menuitemDosen);

        menuitemCourse.setText("Course");
        menuitemCourse.addActionListener(this::menuitemCourseActionPerformed);
        menuitemMahasiswa.add(menuitemCourse);

        jMenuBar1.add(menuitemMahasiswa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuitemCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemCourseActionPerformed
        // TODO add your handling code here:
        CourseForm courseForm = new CourseForm();
        courseForm.setVisible(true);
        courseForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuitemCourseActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        StudentForm mahasiswaForm = new StudentForm();
        mahasiswaForm.setVisible(true);
        // DISPOSE_ON_CLOSE agar jika form mahasiswa disilang, dashboard utama tidak ikut tertutup
        mahasiswaForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void menuitemDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuitemDosenActionPerformed
        // TODO add your handling code here:
        LecturerForm dosenForm = new LecturerForm();
        dosenForm.setVisible(true);
        dosenForm.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_menuitemDosenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dhasboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuitemCourse;
    private javax.swing.JMenuItem menuitemDosen;
    private javax.swing.JMenu menuitemMahasiswa;
    // End of variables declaration//GEN-END:variables
}
