/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author lenov
 */
import java.util.ArrayList;
import model.Course;
import model.KRS;
import model.Lecturer;
import model.Student;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;

/**
 * * @author pyade
 */
public class InputNilai extends javax.swing.JFrame {
    ArrayList<Student> ListMahasiswa = new ArrayList<>();
    ArrayList<Course> ListMK = new ArrayList<>();
    ArrayList<Lecturer> ListLecturers = new ArrayList<>();
    
    final String[] semester = {"1", "2", "3"};
    final DefaultComboBoxModel comboModelSM = new DefaultComboBoxModel(semester);
    
    DefaultComboBoxModel comboModelMhs = new DefaultComboBoxModel();
DefaultComboBoxModel comboModelCourse = new DefaultComboBoxModel();
DefaultComboBoxModel comboModelLecture = new DefaultComboBoxModel();
    
    Student selectedStudent;
    Course selectedCourse;
    KRS krs;
    Lecturer selectedLecturer;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InputNilai.class.getName());

    /**
     * Creates new form InputNilai
     */
    public InputNilai() {
    initComponents();
    
    // Data Dummy untuk simulasi awal
    ListMahasiswa.add(new Student("2515101010", "Nina", "001", "Ilmu Komputer", 20));
    ListMahasiswa.add(new Student("2515101011", "Rehan", "002", "Ilmu Komputer", 21));
    ListMahasiswa.add(new Student("2515101012", "Cokdep", "003", "Ilmu Komputer", 19));
    ListMahasiswa.add(new Student("2515101013", "Ahmad", "004", "Ilmu Komputer", 18));
    ListMahasiswa.add(new Student("2515101014", "Oming", "005", "Ilmu Komputer", 22));
    
    ListMK.add(new Course("010", "OOP", 3, 2));
    ListMK.add(new Course("011", "Matematika Diskrit", 3, 2));
    ListMK.add(new Course("012", "AgamaHindu", 3, 2));
    ListMK.add(new Course("013", "Jaringan Komputer", 3, 2));
      
    ListLecturers.add(new Lecturer("10001011", "Adit", "20010011", "OOP"));
    ListLecturers.add(new Lecturer("10001012", "Wibawa", "20010012", "Matematika Diskrit"));
    ListLecturers.add(new Lecturer("10001013", "Deo", "20010013", "AgamaHindu"));
    ListLecturers.add(new Lecturer("10001014", "Bayu", "20010012", "Jaringan Komputer"));
      
    for(Student mhs : ListMahasiswa){
        comboModelMhs.addElement(mhs);
    }
    for(Course crs : ListMK){
        comboModelCourse.addElement(crs);
    }
    for(Lecturer dsn : ListLecturers){
        comboModelLecture.addElement(dsn);
    }
    
    // ==========================================
    // TAMBAHKAN KODE DI BAWAH INI (PENTING):
    // ==========================================
    cmbNama.setModel(comboModelMhs);
    cmbMataKuliah.setModel(comboModelCourse);
    jComboBoxSM.setModel(comboModelSM);
    cmbLecturer.setModel(comboModelLecture);
    // ==========================================
    
    DefaultTableModel model = (DefaultTableModel) jTableNilai.getModel();
    model.setRowCount(0);
    buttonAdd.setVisible(false);
}
    
    private void setKRS(){
        // Validasi pengaman agar tidak melempar NullPointerException jika komponen belum siap
        if (cmbMataKuliah.getSelectedItem() == null || cmbLecturer.getSelectedItem() == null) {
            return;
        }

        this.selectedCourse = (Course) cmbMataKuliah.getSelectedItem();
        this.selectedLecturer = (Lecturer) cmbLecturer.getSelectedItem();

        try {
            int uas = Integer.parseInt(jTextFieldNilaiUAS.getText().trim());
            int uts = Integer.parseInt(jTextFieldNilaiUTS.getText().trim());
            int sikap = Integer.parseInt(jTextFieldNilaiSikap.getText().trim());
            double rataRata = (uas + uts + sikap) / 3.0;
            
            // Menggunakan constructor KRS(Course, double) sesuai dengan file KRS kamu
            this.krs = new KRS(selectedCourse, rataRata);
            
            // Tambahkan setter di kelas KRS kamu jika ini merah, atau sesuaikan logikanya
            // this.krs.setLecturer(selectedLecturer); 
            
            this.krs.setSemester(String.valueOf(jComboBoxSM.getSelectedItem()));
            
            if(this.krs != null){
                lblOutputGrade.setText(this.krs.getGrade());
            }
        } catch (NumberFormatException e) {
            lblOutputGrade.setText("Nilai Invalid");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbNama = new javax.swing.JComboBox<>();
        jLabelNIM = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbMataKuliah = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldNilaiUAS = new javax.swing.JTextField();
        jTextFieldNilaiUTS = new javax.swing.JTextField();
        jTextFieldNilaiSikap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxSM = new javax.swing.JComboBox<>();
        jLabelJumlahSKS = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblOutputGrade = new javax.swing.JLabel();
        buttonAdd = new javax.swing.JButton();
        cmbLecturer = new javax.swing.JComboBox<>();
        jLabelKodeSKS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableNilai = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Form Input Nilai");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Identitas Mahasiswa");

        jLabel4.setText("Nama");

        cmbNama.addActionListener(this::cmbNamaActionPerformed);

        jLabelNIM.setText("NIM& PRODI");
        jLabelNIM.addActionListener(this::jLabelNIMActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48)
                        .addComponent(cmbNama, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Identitas  MataKuliah");

        jLabel6.setText("Mata kuliah");

        cmbMataKuliah.addActionListener(this::cmbMataKuliahActionPerformed);

        jLabel8.setText("Nilai");

        jTextFieldNilaiUAS.setText("0");

        jTextFieldNilaiUTS.setText("0");

        jTextFieldNilaiSikap.setText("0");

        jLabel9.setText("Semester");

        jComboBoxSM.addActionListener(this::jComboBoxSMActionPerformed);

        jLabelJumlahSKS.setText("JumlahSKS:");

        jLabel11.setText("0");

        jLabel12.setText("Pengampu");

        jLabel13.setText("Nilai Huruf");

        lblOutputGrade.setText("Nilai Huruf");

        buttonAdd.setText("Add");
        buttonAdd.addActionListener(this::buttonAddActionPerformed);

        cmbLecturer.addActionListener(this::cmbLecturerActionPerformed);

        jLabelKodeSKS.setText("Kode dan SKS");
        jLabelKodeSKS.addActionListener(this::jLabelKodeSKSActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(49, 49, 49)
                                .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblOutputGrade, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(cmbLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addComponent(jLabelJumlahSKS)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAdd)
                            .addComponent(jLabel11))
                        .addGap(27, 27, 27))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabelKodeSKS, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(31, 31, 31)
                        .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jTextFieldNilaiSikap, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbMataKuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabelKodeSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNilaiUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNilaiUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNilaiSikap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxSM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelJumlahSKS)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(cmbLecturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblOutputGrade)
                    .addComponent(buttonAdd))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTableNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "NIM", "NAMA", "MataKuliah", "SKS", "Nilai", "Dosen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableNilai);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelNIMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelNIMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNIMActionPerformed

    private void cmbNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNamaActionPerformed
        // TODO add your handling code here:
        this.selectedStudent = (Student) cmbNama.getSelectedItem();
        if(selectedStudent != null){
            // Menggunakan getStudyProgram() (pastikan ini sesuai dengan method di kelas Student kamu)
            jLabelNIM.setText(this.selectedStudent.getNIM() + " | Prodi: " + this.selectedStudent.getStudyProgram());
            
            // Menggunakan getJumlahSks() sesuai dengan struktur data student kamu
            int jumlahSks = this.selectedStudent.getJumlahSKS();
            jLabelJumlahSKS.setText(String.valueOf(jumlahSks));
        }
    }//GEN-LAST:event_cmbNamaActionPerformed

    private void jLabelKodeSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLabelKodeSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelKodeSKSActionPerformed

    private void cmbMataKuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMataKuliahActionPerformed
        // TODO add your handling code here:
        this.selectedCourse = (Course) cmbMataKuliah.getSelectedItem();
        if (selectedCourse != null) {
            jLabelKodeSKS.setText(selectedCourse.getCode() + "| SKS: " + Integer.toString(selectedCourse.getSKS()));
        }
    }//GEN-LAST:event_cmbMataKuliahActionPerformed

    private void jComboBoxSMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSMActionPerformed
        // TODO add your handling code here:
        String semesterDipilih = (String) jComboBoxSM.getSelectedItem();
        if(semesterDipilih != null){
            setKRS();
            buttonAdd.setVisible(true);
        }else{
            buttonAdd.setVisible(false);
        }
    }//GEN-LAST:event_jComboBoxSMActionPerformed

    private void cmbLecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbLecturerActionPerformed
        // TODO add your handling code here:
        this.selectedLecturer = (Lecturer) cmbLecturer.getSelectedItem();
        setKRS(); // Perbarui nilai mutu secara real-time saat dosen dipilih
    }//GEN-LAST:event_cmbLecturerActionPerformed

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed
        // TODO add your handling code here:
        if (selectedStudent != null && krs != null) {
            selectedStudent.addKRS(krs);
            
            // Memastikan data krs, course, dan lecturer tidak null saat dibaca ke dalam tabel
            String namaMatkul = (krs.getCourse() != null) ? krs.getCourse().getCourseName() : "-";
            int sks = (krs.getCourse() != null) ? krs.getCourse().getSKS() : 0;
            String namaDosen = (selectedLecturer != null) ? selectedLecturer.getName() : "-";

            Object[] rowData = {
                selectedStudent.getNIM(), 
                selectedStudent.getName(), 
                namaMatkul, 
                sks, 
                krs.getGrade(), 
                namaDosen
            };
            
            DefaultTableModel model = (DefaultTableModel) jTableNilai.getModel();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_buttonAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
          
        java.awt.EventQueue.invokeLater(() -> new InputNilai().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JComboBox<String> cmbLecturer;
    private javax.swing.JComboBox<String> cmbMataKuliah;
    private javax.swing.JComboBox<String> cmbNama;
    private javax.swing.JComboBox<String> jComboBoxSM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelJumlahSKS;
    private javax.swing.JTextField jLabelKodeSKS;
    private javax.swing.JTextField jLabelNIM;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableNilai;
    private javax.swing.JTextField jTextFieldNilaiSikap;
    private javax.swing.JTextField jTextFieldNilaiUAS;
    private javax.swing.JTextField jTextFieldNilaiUTS;
    private javax.swing.JLabel lblOutputGrade;
    // End of variables declaration//GEN-END:variables
}
