/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.LecturerController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Lecturer;

/**
 *
 * @author lenov
 */
public class LecturerForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LecturerForm.class.getName());
    private final LecturerController controller;
    private int selectedLecturerID = -1; // Menyimpan ID dosen saat baris tabel diklik

    /**
     * Creates new form LecturerForm
     */
    public LecturerForm() {
        initComponents();
        this.controller = new LecturerController();
        loadTableData(); // Menampilkan data langsung dari database ke JTable saat form dibuka
        initTableListener(); // Mendeteksi klik pada baris tabel
    }

    // Fungsi mengambil data dari database lalu memasukannya ke JTable
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) tableDosen.getModel();
        model.setRowCount(0); // Bersihkan isi tabel lama
        
        List<Lecturer> lecturers = controller.getLecturers();
        for (Lecturer l : lecturers) {
            Object[] row = {
                l.getLecturerID(),
                l.getName(),
                l.getNik(),
                l.getNidn(),
                l.getBidangKeahlian()
            };
            model.addRow(row);
        }
    }

    // Fungsi mendeteksi klik baris tabel agar data pindah kembali ke form input
    private void initTableListener() {
        tableDosen.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int selectedRow = tableDosen.getSelectedRow();
                if (selectedRow != -1) {
                    selectedLecturerID = Integer.parseInt(tableDosen.getValueAt(selectedRow, 0).toString());
                    txtNama.setText(tableDosen.getValueAt(selectedRow, 1).toString());
                    txtNIK.setText(tableDosen.getValueAt(selectedRow, 2).toString());
                    // Antisipasi jika data NIDN atau Keahlian bernilai null di database
                    txtNIDN.setText(tableDosen.getValueAt(selectedRow, 3) != null ? tableDosen.getValueAt(selectedRow, 3).toString() : "");
                    txtKeahlian.setText(tableDosen.getValueAt(selectedRow, 4) != null ? tableDosen.getValueAt(selectedRow, 4).toString() : "");
                    
                    btnSimpan.setText("Update"); // Ubah text tombol menjadi Update
                }
            }
        });
    }

    // Fungsi membersihkan kolom isian (form)
    private void clearForm() {
        txtNama.setText("");
        txtNIK.setText("");
        txtNIDN.setText("");
        txtKeahlian.setText("");
        txtPencarian.setText("Pencarian");
        selectedLecturerID = -1;
        btnSimpan.setText("Simpan");
        tableDosen.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        txtNIK = new javax.swing.JTextField();
        txtNIDN = new javax.swing.JTextField();
        txtKeahlian = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        txtPencarian = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDosen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MATER DOSEN");

        jLabel2.setText("Nama");

        jLabel3.setText("NIK");

        jLabel4.setText("NIDN");

        jLabel5.setText("Keahlian");

        txtNama.addActionListener(this::txtNamaActionPerformed);

        txtNIK.addActionListener(this::txtNIKActionPerformed);

        txtNIDN.addActionListener(this::txtNIDNActionPerformed);

        txtKeahlian.addActionListener(this::txtKeahlianActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnDelete.setForeground(new java.awt.Color(204, 0, 51));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(this::btnDeleteActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        txtPencarian.setText("Pencarian");
        txtPencarian.addActionListener(this::txtPencarianActionPerformed);

        btnCari.setText("Cari");
        btnCari.addActionListener(this::btnCariActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNama)
                    .addComponent(txtNIK)
                    .addComponent(txtNIDN)
                    .addComponent(txtKeahlian, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBatal)
                .addGap(79, 79, 79)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(btnSimpan)
                .addGap(42, 42, 42))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(btnCari)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNIDN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtKeahlian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnDelete)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(42, 42, 42))
        );

        tableDosen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama", "NIK", "NIDN", "Keahlian"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDosen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        if (selectedLecturerID == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih data dosen pada tabel terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus dosen ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            int result = controller.deleteLecturer(selectedLecturerID);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data dosen berhasil dihapus!");
                loadTableData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data dosen.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        String name = txtNama.getText().trim();
        String nik = txtNIK.getText().trim();
        String nidn = txtNIDN.getText().trim();
        String keahlian = txtKeahlian.getText().trim();
        
        if (name.isEmpty() || nik.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama dan NIK tidak boleh kosong!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (selectedLecturerID == -1) {
            // MODE INSERT (Dosen Baru)
            // Memanggil Constructor: Lecturer(String nik, String name, String nidn, String bidangKeahlian)
            Lecturer newLecturer = new Lecturer(nik, name, nidn, keahlian);
            
            int result = controller.addLecturer(newLecturer);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data dosen baru berhasil disimpan!");
                loadTableData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menyimpan data dosen.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // MODE UPDATE (Edit data dosen terpilih)
            // Memanggil Constructor Database: Lecturer(int lecturerID, String nik, String nidn, String name)
            Lecturer updatedLecturer = new Lecturer(selectedLecturerID, nik, nidn, name);
            updatedLecturer.setBidangKeahlian(keahlian);
            
            int result = controller.updateLecturer(updatedLecturer);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Data dosen berhasil diperbarui!");
                loadTableData();
                clearForm();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data dosen.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtNIKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIKActionPerformed
        // TODO add your handling code here:
        txtNIDN.requestFocus();
    }//GEN-LAST:event_txtNIKActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String keyword = txtPencarian.getText().trim().toLowerCase();
        DefaultTableModel model = (DefaultTableModel) tableDosen.getModel();
        model.setRowCount(0);
        
        List<Lecturer> lecturers = controller.getLecturers();
        for (Lecturer l : lecturers) {
            if (keyword.isEmpty() || keyword.equals("pencarian") || l.getName().toLowerCase().contains(keyword)) {
                Object[] row = {
                    l.getLecturerID(),
                    l.getName(),
                    l.getNik(),
                    l.getNidn(),
                    l.getBidangKeahlian()
                };
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
        txtNIK.requestFocus();
    }//GEN-LAST:event_txtNamaActionPerformed

    private void txtNIDNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNIDNActionPerformed
        // TODO add your handling code here:
        txtKeahlian.requestFocus();
    }//GEN-LAST:event_txtNIDNActionPerformed

    private void txtKeahlianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeahlianActionPerformed
        // TODO add your handling code here:
        btnSimpanActionPerformed(evt);
    }//GEN-LAST:event_txtKeahlianActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPencarianActionPerformed
        // TODO add your handling code here:
        btnCariActionPerformed(evt);
    }//GEN-LAST:event_txtPencarianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LecturerForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableDosen;
    private javax.swing.JTextField txtKeahlian;
    private javax.swing.JTextField txtNIDN;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPencarian;
    // End of variables declaration//GEN-END:variables
}
